// One entry per group page (/accountants, /letting-agents, ...). Copy follows the website copy doc.
export const GROUPS = [
  {
    slug: 'accountants', name: 'Accountants',
    opening: 'MTD turned one deadline a year into five.',
    headline: 'MTD capacity, without another hire.',
    sub: 'We automate client chasing, data entry and bookkeeping checks, so your team takes on more clients without longer days.',
    familiar: ['Chasing the same client for records, again', 'Retyping bank lines into the software', 'Turning clients away because the team is full'],
    setup: ['Reminders that chase until records arrive', 'Receipts and bank lines read and filed', 'Checks that flag the odd ones for a person'],
    proof: 'Invoice processing: 15 hrs → 1 hr a week.',
    metaTitle: 'AI and automation for accountants — AI Maestro',
    metaDesc: 'MTD capacity without another hire. Client chasing, data entry and checks, automated. Bristol, Manchester and UK-wide.',
  },
  {
    slug: 'letting-agents', name: 'Letting and estate agents',
    opening: 'Missed Saturday’s call? Another agent got the landlord.',
    headline: 'First to reply wins the instruction.',
    sub: 'We answer every enquiry in minutes, book viewings and keep your Renters’ Rights paperwork in order. Evenings and weekends too.',
    familiar: ['Enquiries waiting until Monday', 'Phone tag to book one viewing', 'New rules, more paperwork, same team'],
    setup: ['Replies to every enquiry in minutes, in your wording', 'Viewings booked straight into your diary', 'Tenancy paperwork prepared and tracked'],
    proof: 'CRM updates: 5 hrs a week saved.',
    metaTitle: 'AI and automation for letting agents — AI Maestro',
    metaDesc: 'Reply to every enquiry in minutes, book viewings and stay on top of Renters’ Rights paperwork.',
  },
  {
    slug: 'trades', name: 'Trades',
    opening: 'Quoting at 10pm after a day on the tools?',
    headline: 'Get your evenings back.',
    sub: 'We sort your quotes, invoices and bookings automatically, so the paperwork’s done before you get home.',
    familiar: ['Quotes written at the kitchen table', 'Chasing payment for jobs done weeks ago', 'Missed calls while you’re up a ladder'],
    setup: ['Quotes out the same day', 'Invoices sent and chased for you', 'Jobs booked straight into your diary'],
    proof: 'Invoice processing: 15 hrs → 1 hr a week.',
    metaTitle: 'AI and automation for trades — AI Maestro',
    metaDesc: 'Quotes, invoices and bookings sorted automatically. Get your evenings back.',
  },
  {
    slug: 'agencies', name: 'Agencies',
    opening: 'Client reports eating your Friday afternoons?',
    headline: 'Protect your margin.',
    sub: 'We automate reporting, onboarding and the admin between projects, so your team’s hours go on billable work.',
    familiar: ['Hours of unbilled admin every week', 'The same report, rebuilt every month', 'Turning down work because the team is stretched'],
    setup: ['Reporting that writes itself', 'Onboarding without the chasing', 'Extra build capacity, under your brand'],
    extra: ['Need more hands?', 'We build under your brand and you keep the client. Partner rates available.'],
    proof: 'CRM updates: 5 hrs a week saved.',
    metaTitle: 'AI and automation for agencies — AI Maestro',
    metaDesc: 'Automate reporting and onboarding, or add build capacity under your brand.',
  },
  {
    slug: 'startups', name: 'Startup founders',
    opening: 'Doing sales, support and ops yourself?',
    headline: 'Run like ten. Stay a team of three.',
    sub: 'We automate follow-ups, support and daily admin, so you can grow before you hire.',
    familiar: ['Leads going cold because nobody followed up', 'The same customer questions, every day', 'Hiring before the revenue is there'],
    setup: ['Sales follow-ups that never slip', 'Support answers in your wording, day and night', 'Systems that scale before you hire'],
    extra: ['Need it built?', 'Website or the first version of your app: we design and build those too.'],
    proof: 'LinkedIn content: 3× engagement in 30 minutes a week.',
    metaTitle: 'AI and automation for startups — AI Maestro',
    metaDesc: 'Automate follow-ups, support and admin. Grow before you hire. Websites and apps too.',
  },
];
